apiVersion: 1

datasources:
  - name: GLPI-MySQL
    type: mysql
    access: proxy
    url: 172.28.0.10:3306
    user: glpi_user
    secureJsonData:
      password: changeme
    jsonData:
      database: glpi
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsSkipVerify: false
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
    isDefault: true
    editable: true
