apiVersion: 1

datasources:
  - name: GLPI-MySQL
    type: mysql
    access: proxy
    url: mariadb:3306
    database: ${GLPI_DB_NAME}
    user: ${GLPI_DB_USER}
    secureJsonData:
      password: ${GLPI_DB_PASSWORD}
    jsonData:
      tlsAuth: false
      tlsAuthWithCACert: false
      tlsSkipVerify: true
    isDefault: true
    editable: true
